development:
  adapter: mysql2
  encoding: utf8
  database: independent_project
  username: jwill18
  password: equinox1
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: independent_project
  username: jwill18
  password: equinox1
  host: localhost
  
production:
  adapter: mysql2
  encoding: utf8