development:
  adapter: mysql2
  encoding: utf8
  database: mydbinstance
  username: jwill18
  password: equinox1
  host: mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: mydbinstance
  username: jwill18
  password: equinox1
  host: mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  url: <%= ENV["mysql2://jwill18:equinox1@mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com/mydbinstance?sslca=config/amazon-rds-ca-cert.pem"] %>
  port: <%= ENV["3306"]