development:
  adapter: mysql2
  encoding: utf8
  database: independent_project
  username: jwill18
  password: equinox1
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: independent_project
  username: jwill18
  password: equinox1
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  host: mysql://b719b2c94b2762:6763d52b@us-cdbr-iron-east-04.cleardb.net/heroku_43dda068de5e5ab?reconnect=true