development:
   adapter: mysql2
   database: my_database
   username: root
   password: Gbw77a88
   host: localhost

test:
   adapter: mysql2
   database: my_database
   username: root
   password: Gbw77a88
   host: localhost

production:
   adapter: mysql2
   database: my_database
   username: root
   password: Gbw77a88
   host: localhost