development:
  adapter: mysql2
  encoding: utf8
  database: mydbinstance
  username: jwill18
  password: equinox1
  host: mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: mydbinstance
  username: jwill18
  password: equinox1
  host: mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["mydbinstance"] %>
  username: <%= ENV["jwill18"] %>
  password: <%= ENV["equinox1"] %>
  host: <%= ENV["mydbinstance.ckcwgmv1vxps.us-west-1.rds.amazonaws.com"] %>
  port: 3306